# ./_config.yml
theme: jekyll-theme-hacker
title: Elektronikk og json
description: Dette er siden som viser json og elektronikk
# architect
# theme: jekyll-theme-minimal
# theme: jekyll-theme-architect
